import gradio as gr
from gradio.themes.base import Base
from Database_interface import DataBaseInterface
from FileTextLoader import FileTextLoader
import secret_key

# Database Interface Setup
indexName = "alelladoc"
pineconeEnvironment = "alelladoc"
PineConeinterface = DataBaseInterface(indexName, secret_key.openai_key,
                                      secret_key.pinecone_key,
                                      pineconeEnvironment)

# Define a function to process the uploaded files
def process_files(files):
    if files:
        text_data_from_files = FileTextLoader.load_all_files(files)
        PineConeinterface.import_documents(text_data_from_files)
        return "Files processed successfully."
    return "No files to process."

# Define a function to query the database with a question
def query_question(question):
    output1, output2 = PineConeinterface.query_data(question)
    return output1, output2

# Gradio Interface
with gr.Blocks(theme=Base(), title="Question Answering App using Vector Search + RAG") as demo:
    gr.Markdown("# Question Answering App using Vector Search + RAG Architecture")
    
    # File upload component
    file_upload = gr.File(label="Upload Files (TXT, PDF, DOCX)", file_count="multiple", type="filepath")
    
    # Button for processing files
    process_button = gr.Button("Process Files", variant="primary")
    
    # Status output for file processing
    process_status = gr.Textbox(lines=1, max_lines=1, label="Processing Status")
    
    # Input for text question
    textbox = gr.Textbox(label="Enter your Question:")
    
    # Button for querying the processed files
    query_button = gr.Button("Submit Question", variant="secondary")
    
    # Output boxes for the query results
    with gr.Column():
        output1 = gr.Textbox(lines=1, max_lines=10, label="Output with just Atlas Vector Search")
        output2 = gr.Textbox(lines=1, max_lines=10, label="Output generated by Langchain Vector Search")

    # Connect the process button to the file processing function
    process_button.click(process_files, inputs=file_upload, outputs=process_status)
    
    # Connect the query button to the question answering function
    query_button.click(query_question, inputs=textbox, outputs=[output1, output2])

# Launch the app
demo.launch()
